# Generated by Django 4.0.8 on 2023-01-13 21:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=None),
        ),
    ]
