apiVersion: v1
kind: Service
metadata:
  name: expensify-backend
  labels:
    app: expensify-backend
spec:
  type: NodePort
  selector:
    app: expensify-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32123
---
apiVersion: v1
kind: Service
metadata:
  name: expensify-frontend
  labels:
    app: expensify-frontend
spec:
  type: NodePort
  selector:
    app: expensify-frontend
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32124
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensify-backend
  labels:
    app: expensify-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensify-backend
  template:
    metadata:
      labels:
        app: expensify-backend
    spec:
  
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule

      imagePullSecrets:
      - name: regcred
      containers:
        - image: sasoldevchemicalsdigitalreg.azurecr.io/expensify-backend:latest
          name: expensify-backend
          command: ["/app/entrypoint.sh"]
          args: ["gunicorn", "yet.wsgi:application", "--bind", "0.0.0.0:8000"]
          imagePullPolicy: IfNotPresent

    
          envFrom:
          - secretRef:
              name: expensify-secret

          ports:
            - containerPort: 8000
              name: gunicorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensify-frontend
  labels:
    app: expensify-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensify-frontend
  template:
    metadata:
      labels:
        app: expensify-frontend
    spec:
  
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule

      imagePullSecrets:
      - name: regcred
      containers:
        - image: sasoldevchemicalsdigitalreg.azurecr.io/expensify-frontend:latest
          name: expensify-frontend
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80
              name: nginx
